name: PCM_AUTO_HUNT
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Это вылечит ошибку 403 навсегда
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests joblib xgboost scikit-learn numpy

      - name: Run Analysis
        env:
          SPORTS_API_KEY: ${{ secrets.SPORTS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py

      - name: Save Results
        run: |
          git config --global user.name "PCM-Bot"
          git config --global user.email "bot@pcm.com"
          git add web_export/today_prognosis.json
          git commit -m "Auto-update analysis" || exit 0
          git push
